Add device detection hostcall
fastly/Viceroy pull request #330
Opened 2023-11-06 22:00 UTC by silentbicycle

Add hostcall for device detection, closely patterned on geolocation.

The test that executes the hostcall needs a new SDK, so a second commit comments them out for now. The tests pass locally when built with the new SDK.

2023-11-06 23:36 UTC, acfoltzer requested changes
Just a small copypaste fix, then ready to go

2023-11-06 23:36 UTC, acfoltzer commented on lib/src/config/unit_tests.rs
> +    fn geolocation_has_a_valid_format() {
```suggestion
    fn device_detection_has_a_valid_format() {
```

2023-11-06 23:36 UTC, acfoltzer commented on test-fixtures/src/bin/grpc.rs
> -use fastly::{Backend, Error, Request};
Huh, the formatting step in CI must be missing these if rustfmt changed these despite previous successful commits. Something to worry about later

2023-11-07 13:20 UTC, silentbicycle commented on lib/src/config/unit_tests.rs
> +    fn geolocation_has_a_valid_format() {
Fixed in c6ea312.

2023-11-07 17:27 UTC, acfoltzer approved these changes
thank you!

2023-11-07 18:29 UTC, merged